global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']
    metrics_path: /metrics

  - job_name: 'auth-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /v1/metrics
